### PR TITLE
various fixes for android

### PR DESCRIPTION
**Pull request by mgood7123**

### CODE REVIEW

**Comment by mgood7123** [comment]
could you please merge this, or create an Android branch and allow me write access to it

**Comment by jniemann66** [comment]
It looks ok, except for I don't  really agree with indenting the contents of the namespaces. It's usually standard c++ practice to not indent them - Probably because namespaces are intended to be used for preventing name clashes, and not as a scoping mechanism.

**Comment by mgood7123** [comment]
> It looks ok, except for I don't really agree with indenting the contents of the namespaces. It's usually standard c++ practice to not indent them - Probably because namespaces are intended to be used for preventing name clashes, and not as a scoping mechanism.

oh ok

**Comment by mgood7123** [comment]
reverted namespace indentation

**Pull request merged**
